spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/spring_cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
